{% set version = "2.1.1" %}

package:
  name: urwid
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/urwid/urwid-{{ version }}.tar.gz
  sha256: 7870866e35b00b71b0c9ccdd1281c8e7fac3806d60b9c1075c95dd5dad88d526

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - urwid
    - urwid.tests

about:
  home: http://urwid.org/
  license: LGPL-2.1
  license_file: COPYING
  summary: A full-featured console (xterm et al.) user interface library

extra:
  recipe-maintainers:
    - scopatz
    - asmeurer
    - ocefpaf
