travis:
  secure:
    BINSTAR_TOKEN: X5qhqRO9tLQ6pDzaD6f/og3HLxhfa/8eSjQ+jFp48s6Psg0NT6aQpa+O6QyojR34h/y64wqFYr3FrqYaobDAitK2vOFpoWaLejuLdFv129NQvuy4+eZ5s3NRfnPySTg3dB3gXyXNeAeoxFzUtz9QvRPLkpXwKJKUyrjTKkKyZc2CocgSPPA1PM7aB0sXsRwJaym6aRPOUUp8otWo7On+dManEj6jykPGg1wm6pveFHqFlEa95nol3WbPJR44SPeCfqd/znm3eerAweP2FoIphklqV6dMV1h/QceTz2JRS9LFCif1TellAnGXT8guDCYpS0kkOUV1fwcrdFZy32MTZDu2tn4Kym3/5YIY0jW1LEBItaRMQaq4MNZxM2ux1/ow+cR1I6KeLLa7F4qcPO1tntfMb7MtEVH1g7v99NFKFnEkk+XfEWhuBBgQ4/jpLhw9dxGzn3cZRu3v3Kd9EUc8v8R+L3JcpGfgdLi6QPGcGiuZlC+0RIi2iLFSsbo8O37gMhMJOOTDQUk26QWNAzZnrrGBNMJ8884DUta3aYthhx6UaXbmK3lLDrusf3R6ni9pN8seV/hOcd+axqTA0/rpBCixWiH/5FrVV8niu+yJAVRcQjByBe7zhvK9Zj6+O7XtaVKQytGgx9xnctpNapA4bBbB2t6lcbD23OMIsmeDWTY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
