travis:
  secure:
    BINSTAR_TOKEN: srj8rkduqg8gIDAeyb6JXAHxa5AU5Y+DJbe3yVxWAz+zfCN2RKj9Mpl32kgwTkbarIUj3nOFSEHFJ4JoRte1Eos47Kk3VEWnD5BjUJInHuzvY4AJSXz9B3k6njXMy2Wls9D0n8RzZsJFFbcO9lyjEhEBdzJNPu3+6H07kNIHnJhDErVteHYRvarpOmWiODk4W3FDMgBi+uUV7JxpgIqU7Ma/E4pjpwevuJLdZ/hKDkh+FVfKFdw8Y/YJlEDTbjeEnvk2UH1hkfQbPLtHbjc3GdPdYn5S5LNcXPY95kzN+Df4LuqL35ToOWP/B3HgxEFq63KsiMpzBveH693kR//wvnd+Qz3jMu7irlg2DmuuC01Bv4OiFqstWZ5E1+T6BSavONHOM7VsOHGaIPIfeQ9iYXxGCvfx73D862YvyZG6DNtwGgc5lVtlfOS/LeP4fGyZ9EgyWe7BlXmTgpMyAf0ALzhIbC1MjBI6uy/4yjMsiublhqMUbVSYrdi7fS1o0xqlP19jXDdvfsfJhvMTipkLw2oY8QR4vcoKbvpcLfjTknE0GOYch+mBlHjbWBBGBlTw+C4NGzBE7xAQwe7kB+XYu6ma4dLJEbzwZ5NEV6aSBu/Hd9eOEoMDJT+XiKQe+d4ITyk8rK5mccZf/xrwnGZ/Lj+qlGiFluuFjyZzHpGg24I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
